### ISSUE TITLE
meta: update this repo!

### ISSUE THREAD

**Issue by nikhita** [nikhita/gsoc-meta-k8s#32]
- [x] Add weekly summaries links in README
- [x] Update all weekly summaries [in progress]
- [x] Add all PRs/issues (see https://github.com/nikhita/github-contrib)
